### PR TITLE
chore: gitignore for IDEs

### PR DESCRIPTION
**Pull request by fetis**
# Change Type

* [ ] Feature
* [x] Chore
* [ ] Bug Fix

# Change Level
n/a

# Further Information (screenshots, bug report links, etc.)
- Added strings for JetBrains IDEs and VS Code
- fixed indentation in `cli/package.json`

### CODE REVIEW

**Comment by enykeev** [comment]
How about we use something like that instead https://www.gitignore.io/api/osx,node,intellij,visualstudio?

**Comment by zacanger** [comment]
Whew, that's a lot of stuff to ignore @enykeev. A lot of those files won't ever show up in this project (I doubt anyone is using ReSharper or MSSQL in a Node project), so I think it might be better to just add things to the ignores files as they come up.

@fetis could you add those same lines to the `.dockerignore`?

**Comment by fetis** [comment]
> How about we use something like that instead https://www.gitignore.io/api/osx,node,intellij,visualstudio?

I saw this generator and in my opinion it does too much. I would like to keep in ignore only required stuff.

**Comment by fetis** [comment]
> could you add those same lines to the .dockerignore?

@zacanger synced with .gitignore

**Pull request closed without merging**
