### PR TITLE
docs: point to Arch Linux package

### PR DESCRIPTION
**Pull request by dmfay**
hi! I'm just starting to check this out but I thought I'd install The Arch Way™, so here's a package.

### CODE REVIEW

**Comment by olingern** [comment]
Nice. I'm on arch, too. I'll test this out

**Comment by toddself** [comment]
You'll need a different node version -- I don't believe this will under node 6.

**Comment by dmfay** [comment]
@toddself I'm not following -- Arch ships [node 11.15.0](https://www.archlinux.org/packages/community/x86_64/nodejs/) right now, so you'd have to go outside its package management ecosystem to be running 6.

**Comment by toddself** [comment]
Ah sorry - the deps list has `nodejs6-bin` listed

image

But it's that annoying substitutes list.

**Pull request closed without merging**
