### PR TITLE
Add snap pkg builds

### PR DESCRIPTION
**Pull request by 1stvamp**
# Change Type

* [x] Feature
* [ ] Chore
* [ ] Bug Fix

# Change Level

* [ ] major
* [ ] minor
* [x] patch

# Further Information (screenshots, bug report links, etc.)

This adds a build file (`snapcraft.yaml`) for building a [snap package](https://snapcraft.io/), which can be pushed up to the snap store (I have published an initial _edge channel_ release [here](https://snapcraft.io/entropic-ds) and would be happy to hand over ownership to current maintainers) and installed on any Linux that supports `snapd`.

~Following up, and given credentials for talking to the snap store, `.travis.yml` could be updated to continuously push `master` builds to the aforementioned edge channel.~
Actually you can add a GitHub integration (webhook) easily from snapcraft.io to do the continuous builds on Canonical's build farm and published continuously to the store. 🎉

# Checklist

* [ ] Added tests / did not decrease code coverage
* [x] Tested in supported environments (common browsers or current Node)

### CODE REVIEW

**Comment by 1stvamp** [comment]
I welcome feedback on where _how to build a snap package` instructions should live (the current `cli/README.md` seems appropriate except it currently has info purely about using the `ds` util, not about developing/packaging it for consumption).

For the record the usage for building a snap is this:

```sh
cd cli/
snapcraft

# This gives you a ds_master_amd64.snap file
# You can install and test it, --dangerous means ignore the lack of signature for the package that comes when publishing it to the store
snap install --dangerous ds_master_amd64.snap

# To publish it to the snap store
snapcraft login # unless already logged in
snapcraft push ds_master_amd64.snap

# If it's good release it to the edge channel
snapcraft release entropic-ds $REVISION edge

# It should show up momentarily in the store
snap find entropic-ds
```

**Comment by zacanger** [comment]
Woah this is awesome. This is all it takes to build a snap? That's so nice!

**Comment by zacanger** [comment]
Tested on Ubuntu 18.04, snap version 2.39, and the install works, but the command installed is `entropic-ds.ds`. Is that intentional?

**Comment by 1stvamp** [comment]
Ah yes forgot to mention this, once the snap is official the `ds` alias can
be requested on the snapcraft forum, this is so snaps that override
executables in the Debian/Ubuntu archives, well, don't. 😁

**Comment by zacanger** [comment]
Gotcha, that makes sense.

**Pull request closed without merging**
